services:
  sewainaja-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sewainaja-admin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production

  sewainaja-api:
    build:
      context: ./functions
      dockerfile: Dockerfile
    container_name: sewainaja-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./functions/.env
    volumes:
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - UPLOAD_ROOT=/app/uploads

volumes:
  uploads:
